import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Navbar from '../component/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
                 
      <main className='mx-10 mt-16'>
        <div className='flex  '>
          <div className='w-1/2 flext-col mx-auto mt-16'>
            <h1 className='text-6xl font-bold text-gray-600'>Building Success.</h1>
            <p className='mt-8 text-lg text-gray-600 text-justify'>Serviam Manpower Private Limited is one of the top HR consultancy agencies in Mumbai. We are a fast-growing and exciting manpower consultancy that enables companies to get the best candidates for their job offers.</p>
            <ol className='mt-8 text-lg text-gray-600 ml-5'>
              <li>Committed to Greatness.</li>
              <li>Vast experience in Recruiting.</li>
              <li>Strong Networking.</li>
              <li>Cost-effective solutions.</li>
            </ol>
            <div>
              <Link href={'/contactus'}><button className='bg-orange-500 w-fit px-7 mt-5 py-3 hover:bg-black rounded-md my-2 font-bold text-white text-lg'>Contact Us</button></Link>
            </div>
          </div>
          <div className='flex mx-auto'>
            <Image src="/image.jpg" width={600} height={500} className='rounded-xl'></Image>
          </div>
        </div>

        <div className='text-xl text-center mt-20 font-semibold'>Trusted by</div>

        <div className='mt-10 flex justify-between '>
          <div>
            <Image src='/client3.jpg' width={200} height={70}></Image>
          </div>
          <div>
            <Image src='/client2.jpg' width={200} height={70}></Image>
          </div>
          <div>
            <Image src='/client.jpg' width={200} height={70}></Image>
          </div>
          <div>
            <Image src='/client4.jpg' width={200} height={70}></Image>
          </div>
          <div>
            <Image src='/client3.jpg' width={200} height={70}></Image>
          </div>
        </div>

        <div className='mt-20 flex justify-between'>
          <div className='flex flex-col w-1/2'>
            <h1 className='text-4xl font-bold text-gray-600 hover:text-blue-500'>Who We Are?</h1>
            <p className='text-justify text-lg text-gray-600 mt-5'>Serviam Manpower Private Limited is one of the top HR consultancy agencies in Mumbai. We are a fast-growing and exciting manpower consultancy that enables companies to get the best candidates for their job offers. Established in 2010, we at Serviam, with our motto, ‘Dedicated to Serve’ pride ourselves in providing the best human capital solutions by conducting the rigorous and careful procedure of finding the perfect fit and best-qualified leadership candidates for our clients in several sectors. We specialize in Headhunting, Executive search and selection, and leadership at the international, cross-border, and local levels. With a multifaceted team of process engineers, technology evangelists, search professionals, and recruitment consultants that possess the right blend of knowledge and experience, we ensure fast and effective delivery of the best talents to our clients.</p>
          </div>
          <div className='right flex mx-auto'>
            <Image src='/image2.jpg' width={420} height={394}></Image>
          </div>
        </div>



        <div className='text-4xl font-bold mx-auto w-fit mt-20 text-gray-600  hover:text-blue-500'>Why Serviam</div>

        <div className='mt-20 flex justify-between '>
          <div className='left flex mx-auto '>
            <Image src='/image3.jpg' width={500} height={387}></Image>
          </div>
          <div className='right flex flex-col w-1/2 ml-40'>
            <div>
              <h1 className='text-2xl font-bold'>Search Intelligence</h1>
              <p className='text-justify text-md text-gray-600 mt-3'>Our services are driven by a deep understanding of our clients’ companies. We call this approach ‘search intelligence.’ We deliver the best candidates by considering a wide range of prospects and adhering to our true fit philosophy.</p>
            </div>
            <div className='mt-5'>
              <h1 className='text-2xl font-bold'>Client-Focused.</h1>
              <p className='text-justify text-md text-gray-600 mt-3'>Our total quality approach is client focused. We assist our clients by learning about their culture, assessing organizational needs, recommending actions, and facilitating change.</p>
            </div>
            <div className='mt-5'>
              <h1 className='text-2xl font-bold'>Building Long-term Partnerships.</h1>
              <p className='text-justify text-md text-gray-600 mt-3'>We develop comprehensive relationships with our clients and provide lasting support during the recruitment and development of the people who will grow their businesses.</p>
            </div>
            <div className='mt-5'>
              <h1 className='text-2xl font-bold'>Guaranteed results.</h1>
              <p className='text-justify text-md text-gray-600 mt-3'>Serviam’s true measure of success is our ability to deliver guaranteed results. Our advanced research-validated processes and methodologies enable us to offer our clients value for money and the best return on talent. With our expertise in headhunting, staffing solutions, and permanent hiring services, we are moving towards greatness every day to become the best recruitment agency in India.</p>
            </div>
          </div>

        </div>

        <div className='text-4xl font-bold flex mx-auto text-center mt-20 text-gray-600 hover:text-blue-500'>Recruit efficient and suitable leaders and professionals for your company with Serviam.</div>

        <div className='text-4xl font-bold mx-auto flex justify-center mt-10 text-gray-600 hover:text-blue-500'>Services</div>

        <div className='flex mx-auto mt-10 space-x-5 text-white'>
          <div className='bg-blue-500 rounded-2xl py-7 px-7 w-1/2'>
            <Image src='/user.svg' width={50} height={50}></Image>
            <h1 className='text-xl font-bold my-5'>Executive search and selection</h1>
            <p className='text-justify text-md '>We are true headhunters that provide proactive and research-based recruiting services to organizations seeking the very best executive talent to lead their companies.</p>
          </div>
          <div className='bg-blue-500 rounded-2xl py-7 w-1/2  px-7'>
            <Image src='/user.svg' width={50} height={50}></Image>
            <h1 className='text-xl font-bold my-5'>Permanent hiring.</h1>
            <p className='text-justify'>Finding skilled, enthusiastic employees with the essential abilities to suit our client’s long-term and strategic objectives defines our permanent hiring service.</p>
          </div>
        </div>
        <div className='flex mx-auto space-x-4 text-white mt-4'>
          <div className='bg-blue-500 rounded-2xl py-7 w-1/2 px-7'>
            <Image src='/user.svg' width={50} height={50}></Image>
            <h1 className='text-xl font-bold my-5'>RPO</h1>
            <p className='text-justify'>Serviam makes it easier for organizations to acquire the right talent by offering effective end-to-end RPO solutions that boost agility, and help them drive cost and quality benefits as well as reduce fill time.</p>
          </div>
          <div className='bg-blue-500 rounded-2xl w-1/2 py-7 px-7'>
            <Image src='/user.svg' width={50} height={50}></Image>
            <h1 className='text-xl font-bold my-5'>Professional Staffing.</h1>
            <p className='text-justify'>Staffing at Serviam is a process of employee recruitment, screening, and selection for organizations looking for short-term hiring needs. We take care of hiring fresh candidates, payroll, compliance, and many more for our clients.</p>
          </div>
        </div>

        <div className='py-2 px-7 rounded-md mt-5 text-lg font-bold bg-orange-500 text-white w-fit mx-auto hover:bg-gray-600  active:bg-gray-400'>
          <button>See all</button>
        </div>

        <div className='text-4xl font-bold text-center mt-20 hover:text-blue-500'>Awards</div>
        <div className='flex justify-between mx-20 mt-20'>
          <div>
            <Image src='/award1.jpg' width={100} height={100}></Image>
          </div>
          <div>
            <Image src='/award2.jpg' width={300} height={100}></Image>
          </div>
          <div>
            <Image src='/award3.jpg' width={300} height={100}></Image>
          </div>
          <div>
            <Image src='/award4.jpg' width={100} height={100}></Image>
          </div>
        </div>

        
        <div className='mt-32'>
          <h1 className='text-4xl font-bold text-gray-700'>Contact with us</h1>
        </div>

        <div className='mt-5 flex justify-between mb-40 '>
          <div className='flex flex-col w-1/2 justify-center'>
            <input type="text" placeholder='Name' className='py-3 px-3 my-2 border-2 border-gray-100 rounded-md' />
            <input type="text" placeholder='City' className='py-3 px-3 my-2 border-2 border-gray-100 rounded-md' />
            <input type="Phone" placeholder='Contact Number' className='py-3 px-3 my-2 border-2 border-gray-100 rounded-md' />
            <input type="text" placeholder='Email' className='py-3 px-3 my-2 border-2 border-gray-100 rounded-md' />
            <input type="text" placeholder='Message' className='py-3 px-3 my-2 border-2 border-gray-100 rounded-md' />
            <button className='bg-orange-500 w-fit px-10 py-3 rounded-md my-2 font-bold text-white text-lg'>Submit</button>
          </div>
          <div className='flex mx-auto'>
            <Image src='/image4.jpg' width={540} height={458}></Image>
          </div>
        </div>


      </main >

    </div >
  )
}
